### ISSUE TITLE
Titles are not converted

### ISSUE THREAD

**Issue by mikhailnov** [legionus/md2man#1]
I converted this README.md https://github.com/mikhailnov/snr/blob/master/README.md and the resulting man page did not include level-2 titles from markdown file, e.g. `## Usage examples` was lost.

**Comment by legionus** [comment]
I rewrote the `RoffRenderer` with the `gopkg.in/russross/blackfriday.v2`.
Try the version from the master.

**Comment by mikhailnov** [comment]
`strings.ReplaceAll` requires golang >= 1.12. I tried to convert the same file, the output contains errors, e.g.: `{Hardbreak}` is in the output

**Comment by mikhailnov** [comment]
I ahve retested it, now the result is much better, thanks a lot!
